name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@main

      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./
          host: ${{ vars.SSH_HOST }}
          remote: ${{ vars.SSH_DIR }}
          user: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}